### PR TITLE
cdpm2: parallel, thermal, damage compression

### PR DESCRIPTION
**Pull request by githubgrasp**
Changed cdpm2 to avoid problem with parallel computations. 
Also introduced reduced strain so that thermal/shrinkage strains can be considered
Modified codes for tensile and compressive damage so that in the iterative approach the correct starting stress is considered.

### CODE REVIEW

**Comment by bpatzak** [comment]
Hi Peter, looks good, only one comment: is there any specific reason why you have replaced 
`inelasticStrainVector.subtract(plasticStrainVector);`
by 
`for ( int i = 1; i <= inelasticStrainVector.giveSize(); ++i ) {
    inelasticStrainVector.at(i) -= plasticStrainVector.at(i);
}   
`
you made similar changes in different locations. I don't see much reason for this (except I overlooked one) and this just makes the generated code bigger.

**Comment by githubgrasp** [comment]
Hi Borek

 The history variables in CDPM2 have originally size 6 in the status. However, I have in CDPM2 a giveRealStress_1D and giveRealStress_3D. For 1D, the strain is given as size 1. I then subtract the plastic strain, which has originally size 6 ... To avoid problem with that I write it as shown. (Alternatively, I could resize the plasticStrainVector once I have called it?)

Peter

**Comment by bpatzak** [comment]
Hi Peter, 
ok. So what about creating the state variables with correct size from the beginning? The CreateStatus has gp as parameter, which knows its material mode, so the size of state vectors can be determined. See MPlasticMaterial2 and MPlasticMaterial2Status for an example.
Borek

**Comment by githubgrasp** [comment]
Ok, I will change it. 

Peter

**Comment by githubgrasp** [comment]
Strange. On my system the code compiles without problems. Seems to be some unnecessary override's.

**Comment by githubgrasp** [comment]
OK, it seems to be fine now. I still get a warning concerning the initialisation of the plasticStrain and tempReducedStrain, which I do not understand. However, the tests pass.

**Pull request merged**
