### PR TITLE
add lattice and periodic cell elements 

### PR DESCRIPTION
**Pull request by githubgrasp**
Add lattice elements and materials. 
Add periodic elements and vtkxml modules

### CODE REVIEW

**Comment by bpatzak** [comment]
Hi Peter,
can you resolve conflicts before I can accept the pull request.

**Comment by githubgrasp** [comment]
Hi Borek
I have resolved the conflicts now.
Peter

**Comment by bpatzak** [comment]
Hi Peter, 
There are four test failing:
The following tests FAILED:
	115 - test_sm_lattice_damageviscoelastic_01.in (SEGFAULT)
	116 - test_sm_lattice_damageviscoelastic_02.in (SEGFAULT)
	117 - test_sm_lattice_plastdamviscoel_01.in (Failed)
	118 - test_sm_lattice_plastdamviscoel_02.in (Failed)
Errors while running CTest

Also I can see a lot of warning during compilation of lattice elements. Would be nice to fix them before merging. I understand that warnings are due to recent changes, I can fix them by myself, but fix the tests, please.
Borek

**Comment by githubgrasp** [comment]
No problem. I will fix the tests and the warnings.

**Pull request merged**
